name: ğŸ” Contexts
run-name: Context

on:
    push

jobs:
    get-context:
        name: ğŸ¤²ğŸ¼ Get context
        runs-on: ubuntu-22.04
        steps:
            - name: Getting context
              run: | 
                echo "event= ${{ github.event_name}}"
                echo "ref= ${{ github.ref}}"
                echo job_status= ${{ job.status }}"